import jsPDF from "jspdf";
import type { Bill, ShopAccount } from "./shop";

export function generateBillPdf(bill: Bill, shop: ShopAccount) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 48;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(shop.shopName, 40, y);
  y += 16;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const head = [
    `${shop.address}, ${shop.city} - ${shop.pincode}`,
    `Phone: ${shop.phone}   Email: ${shop.email}`,
    `Drug Licence (Retail): ${shop.drugLicenseRetail}${shop.drugLicenseWholesale ? `   Wholesale: ${shop.drugLicenseWholesale}` : ""}`,
    `GSTIN: ${shop.gstin}   PAN: ${shop.pan}`,
    `Pharmacist: ${shop.pharmacistName} (Reg. ${shop.pharmacistRegNo}, ${shop.pharmacistCouncil})`,
  ];
  head.forEach((line) => {
    doc.text(line, 40, y);
    y += 12;
  });

  y += 6;
  doc.setDrawColor(200);
  doc.line(40, y, W - 40, y);
  y += 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("TAX INVOICE", 40, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`Bill No: ${bill.id}`, W - 40, y - 12, { align: "right" });
  doc.text(`Date: ${new Date(bill.at).toLocaleString("en-IN")}`, W - 40, y, { align: "right" });
  y += 16;
  doc.text(`Customer: ${bill.customerName || "Walk-in"}`, 40, y);
  if (bill.customerPhone) doc.text(`Phone: ${bill.customerPhone}`, 200, y);
  y += 20;

  doc.setFont("helvetica", "bold");
  doc.text("Item", 40, y);
  doc.text("Pack", 250, y);
  doc.text("Qty", 380, y, { align: "right" });
  doc.text("Rate", 450, y, { align: "right" });
  doc.text("Amount", W - 40, y, { align: "right" });
  y += 6;
  doc.line(40, y, W - 40, y);
  y += 14;
  doc.setFont("helvetica", "normal");

  bill.lines.forEach((l) => {
    if (y > 740) {
      doc.addPage();
      y = 60;
    }
    doc.text(l.name.slice(0, 40), 40, y);
    doc.text(l.pack.slice(0, 22), 250, y);
    doc.text(String(l.qty), 380, y, { align: "right" });
    doc.text(l.price.toFixed(2), 450, y, { align: "right" });
    doc.text((l.price * l.qty).toFixed(2), W - 40, y, { align: "right" });
    y += 16;
  });

  y += 4;
  doc.line(320, y, W - 40, y);
  y += 16;
  const row = (label: string, value: string, bold = false) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.text(label, 450, y, { align: "right" });
    doc.text(value, W - 40, y, { align: "right" });
    y += 16;
  };
  row("Subtotal", `Rs ${bill.subtotal.toFixed(2)}`);
  row("GST (12%)", `Rs ${bill.gst.toFixed(2)}`);
  row("Total", `Rs ${bill.total.toFixed(2)}`, true);

  y += 20;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("OTC & wellness products only. Goods once sold are not returnable unless defective.", 40, y);
  y += 12;
  doc.text(`Generated by SwiftMed Store on ${new Date().toLocaleString("en-IN")}`, 40, y);

  doc.save(`${bill.id}.pdf`);
}